spring:
  #카카오 로그인
  security:
    oauth2:
      client:
        registration:
          kakao:
            #client-id: ENC(3490cacb0caf44f5940e4b7dcad93ad4)
            client-id: 3490cacb0caf44f5940e4b7dcad93ad4
            #client-secret: ENC(zrLm9zt0SW7wbQ3AGoinjzO2OsQLIMAO)
            client-secret: zrLm9zt0SW7wbQ3AGoinjzO2OsQLIMAO
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/kakao/callback
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
            
  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rememberbday?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mysql
    

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

#jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    key: yuniSecurity